
export const GET_APPLICANT_ID = 'GET_APPLICANT_ID';
export const GET_APPLICANT_DETAILS= 'GET_APPLICANT_DETAILS';

export const GET_IMAGE_URL= 'GET_IMAGE_URL';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';